name: release

on:
  workflow_dispatch:
    inputs:
      versionType:
        type: choice
        description: "The version of the release. Select 'current' to use the current version, or 'patch', 'minor', or 'major' to bump the version."
        required: true
        options:
          - 'current'
          - 'patch'
          - 'minor'
          - 'major'

jobs:
  run-test:
    name: Run Tests
    uses: platformatic/meraki/.github/workflows/test.yml@main

  # We create a tag and a release draft from the tag, then we publish the release. 
  prepare-draft-with-bump:
    if: github.event.inputs.versionType != 'current'
    name: Prepare release tag with version bump
    needs: run-test
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@v4
    - id: version-bump 
      name:  'Automated Version Bump'
      uses:  'phips28/gh-action-bump-version@master'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        version-type:  ${{ github.event.inputs.versionType }}
        tag-prefix:  'v'
    - name: get current version
      id: get-current-version
      run: |
        echo "CURRENT_VERSION=`cat package.json | jq -r .version`" >> $GITHUB_OUTPUT
      shell: bash
    - name: Create Draft Release
      uses: platformatic/meraki/.github/workflows/release-draft.yml@main
      with:
        tag_name: v${{ steps.get-current-version.outputs.CURRENT_VERSION }}
      secrets: inherit

  prepare-draft:
    if: github.event.inputs.versionType == 'current'
    name: Prepare release tag with current version
    needs: run-test
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@v4
    - name: get current version
      id: get-current-version
      run: |
        echo "CURRENT_VERSION=`cat package.json | jq -r .version`" >> $GITHUB_OUTPUT
      shell: bash
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        custom_tag: v${{ steps.get-current-version.outputs.CURRENT_VERSION }}
    - name: Create Draft Release
      uses: platformatic/meraki/.github/workflows/release-draft.yml@main
      with:
        tag_name: v${{ steps.get-current-version.outputs.CURRENT_VERSION }}
      secrets: inherit

  release:
    name: Release 
    runs-on: ubuntu-latest
    steps:  
    - name: Get last Draft
      id: last_release
      uses: InsonusK/get-latest-release@v1.1.0 # https://github.com/InsonusK/get-latest-release
      with:
        myToken: ${{ secrets.GITHUB_TOKEN }}
        exclude_types: "release|prerelease"
        view_top: 1

    - name: "Print draft info"
      run: |
          echo "Releasing:"
          echo "id: ${{ steps.last_release.outputs.id }}"
          echo "name: ${{ steps.last_release.outputs.name }}"
          echo "tag_name: ${{ steps.last_release.outputs.tag_name }}"
          echo "created_at: ${{ steps.last_release.outputs.created_atd }}"

    - name: "Publish Release"
      uses: eregon/publish-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ steps.last_release.outputs.id }}

    - name: Edit Release
      uses: irongut/EditRelease@v1.2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        id: ${{ steps.last_release.outputs.id }}
        name: "Platformatic Meraki ${{ steps.last_release.outputs.TAG }}"

