name: release-draft 

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      tag_name:
        type: string
      apply_win_sign:
        type: boolean
        default: false

  push:
    branches:
      - main

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  run-test:
    uses: platformatic/meraki/.github/workflows/test.yml@main

  release-linux:
    needs: run-test 
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - run: echo "Creating Linux draft release for tag ${{ inputs.tag_name }}"
      - uses: actions/checkout@v4.2.0
        with:
          ref: ${{ inputs.tag_name }}
          fetch-depth: 0 # https://github.com/actions/checkout/issues/1471
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build:linux
      - run: npm run release:linux

  release-windows:
    needs: run-test 
    runs-on: windows-latest
    timeout-minutes: 15
    env: 
      DIGICERT_FINGERPRINT: ${{ secrets.SM_CODE_SIGNING_CERT_SHA1_HASH }}
      SM_HOST: ${{ secrets.SM_HOST }}
      SM_API_KEY: ${{ secrets.SM_API_KEY }}
      SM_CLIENT_CERT_FILE: D:\\Certificate_pkcs12.p12
      SM_CLIENT_CERT_PASSWORD: ${{ secrets.SM_CLIENT_CERT_PASSWORD }}
      APPLY_WIN_SIGN: ${{ inputs.apply_win_sign }}
    steps:
      - run: echo "Creating Windows release for tag ${{ inputs.tag_name }}"
      - run: echo "Siging in windows ${{ inputs.apply_win_sign }}"
      - name: Set up certificate 
        run: | 
          echo "${{ secrets.SM_CLIENT_CERT_FILE_B64 }}" | base64 --decode > /d/Certificate_pkcs12.p12 
        shell: bash

      - name: Set variables
        id: variables
        run: |
          dir
          echo "::set-output name=version::${GITHUB_REF#refs/tags/v}"
          echo "::set-output name=CERTIFICATE_NAME::gt-certificate"
          echo "C:\Program Files (x86)\Windows Kits\10\App Certification Kit" >> $GITHUB_PATH
          echo "C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools" >> $GITHUB_PATH
          echo "C:\Program Files\DigiCert\DigiCert Keylocker Tools" >> $GITHUB_PATH
        shell: bash

      - name: Setup Keylocker KSP on windows 
        if: env.APPLY_WIN_SIGN == 'true'
        run: | 
          curl -X GET  https://one.digicert.com/signingmanager/api-ui/v1/releases/Keylockertools-windows-x64.msi/download -H "x-api-key:%SM_API_KEY%" -o Keylockertools-windows-x64.msi 
          msiexec /i Keylockertools-windows-x64.msi /quiet /qn
          smksp_registrar.exe list 
          smctl.exe keypair ls 
          C:\Windows\System32\certutil.exe -csp "DigiCert Signing Manager KSP" -key -user
        shell: cmd 
      
      - name: Certificates Sync       
        if: env.APPLY_WIN_SIGN == 'true'
        run: |
          smctl windows certsync
        shell: cmd

      - name: SMCTL healthcheck
        if: env.APPLY_WIN_SIGN == 'true'
        run: |
          smctl healthcheck
        shell: cmd 
        
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - uses: actions/checkout@v4.2.0
        with:
          ref: ${{ inputs.tag_name }}
          fetch-depth: 0 # https://github.com/actions/checkout/issues/1471
      - run: npm ci 
      - run: npm run build:win
      - run: npm run release:win

  release-mac-arm64:
    needs: run-test 
    runs-on: macos-14
    timeout-minutes: 15
    env: 
      CSC_LINK: ${{ secrets.CSC_LINK }}
      CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
      APPLE_ID: ${{ secrets.APPLE_ID }}
      APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
    steps:
      - run: echo "Creating Mac release for tag ${{ inputs.tag_name }}"
      - uses: actions/checkout@v4.2.0
        with:
          ref: ${{ inputs.tag_name }}
          fetch-depth: 0 # https://github.com/actions/checkout/issues/1471
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      # for building the native modules with python 3.12
      - run: brew install python-setuptools
      - run: npm ci
      - run: npm run build
      - run: npm run release:mac:arm64

  release-mac-x64:
    needs: run-test 
    runs-on: macos-13
    timeout-minutes: 15
    env: 
      CSC_LINK: ${{ secrets.CSC_LINK }}
      CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
      APPLE_ID: ${{ secrets.APPLE_ID }}
      APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
    steps:
      - run: echo "Creating Mac release for tag ${{ inputs.tag_name }}"
      - uses: actions/checkout@v4.2.0
        with:
          ref: ${{ inputs.tag_name }}
          fetch-depth: 0 # https://github.com/actions/checkout/issues/1471
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      # for building the native modules with python 3.12
      - run: sudo -H pip install setuptools
      - run: npm ci
      - run: npm run build
      - run: npm run release:mac:intel

