name: release 

on:
  workflow_dispatch:
  workflow_call:
  push:
    # branches:
      # - main

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  # release-linux:
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 15
  #   steps:
  #     - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: 18
  #     - run: npm ci
  #     - run: npm run build:linux
  #     - run: npm run release:linux

  release-windows:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
      - name: Set up certificate 
        run: | 
          echo "${{ secrets.SM_CLIENT_CERT_FILE_B64 }}" | base64 --decode > /d/Certificate_pkcs12.p12 
        shell: bash
      - name: Set variables for signing
        id: variables 
        run: | 
          echo "::set-output name=version::${GITHUB_REF#refs/tags/v}" 
          echo "SM_HOST=${{ secrets.SM_HOST }}" >> "$GITHUB_ENV" 
          echo "SM_API_KEY=${{ secrets.SM_API_KEY }}" >> "$GITHUB_ENV" 
          echo "SM_CLIENT_CERT_FILE=D:\\Certificate_pkcs12.p12" >> "$GITHUB_ENV" 
          echo "SM_CLIENT_CERT_PASSWORD=${{ secrets.SM_CLIENT_CERT_PASSWORD }}" >> "$GITHUB_ENV" 
        shell: bash 
      - uses: actions/setup-java@v4
        with:
          distribution: 'microsoft' 
          java-version: '17'
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - run: java -jar ./sign-win/jsign-5.0.jar
        
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: 18
      # - run: npm ci
      # - run: npm run build:win
      # - run: npm run release:win

  # release-mac:
  #   runs-on: macos-latest
  #   timeout-minutes: 15
  #   steps:
  #     - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: 18
  #     - run: npm ci
  #     - run: npm run build
  #     - run: npm run release:mac

