name: release 

on:
  workflow_dispatch:
  workflow_call:
  push:
    # branches:
      # - main

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  # release-linux:
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 15
  #   steps:
  #     - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: 18
  #     - run: npm ci
  #     - run: npm run build:linux
  #     - run: npm run release:linux

  release-windows:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'microsoft' # See 'Supported distributions' for available options
          java-version: '17'
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - run: java -jar ./sign-win/jsign-5.0.jar
        
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: 18
      # - run: npm ci
      # - run: npm run build:win
      # - run: npm run release:win

  # release-mac:
  #   runs-on: macos-latest
  #   timeout-minutes: 15
  #   steps:
  #     - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: 18
  #     - run: npm ci
  #     - run: npm run build
  #     - run: npm run release:mac

